### ISSUE TITLE
Amazing package! Nonlinear objective?

### ISSUE THREAD

**Issue by mohamed82008** [ZIB-IOL/Boscia.jl#102]
Hi, thanks for this great package. Does Boscia support non-convex nonlinear objectives?

**Comment by matbesancon** [comment]
Thanks! Yes it does support non-convex objectives as long as they are differentiable, it will not produce a global optimum in that case but a stationary point

**Comment by mohamed82008** [comment]
Sounds reasonable. I will give it a shot. Thanks.
